DROP TABLE IF EXISTS people;
CREATE TABLE people (
	id INTEGER PRIMARY KEY,
	name TEXT, 
	hometown TEXT,
	sign TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER gang BEFORE UPDATE ON people BEGIN
UPDATE pets SET updated_at = CURRENT_TIMESTAMP WHERE ID = new.id;
END;